[package]
name = "breakpoint"
version = "0.1.0"
edition = "2024"

license = "MIT"

[[bin]]
name = "breakpoint"
path = "main.rs"

[lints]
workspace = true

[dependencies]
miralis_abi = { path = "../../crates/abi" }
