[package]
name = "default"
version = "0.1.0"
edition = "2021"

license = "MIT"

[[bin]]
name = "default"
path = "main.rs"

[dependencies]
miralis_abi = { path = "../../crates/abi" }
log = { workspace = true }
