[package]
name = "miralis_abi"
version = "0.1.0"
edition = "2024"

license = "MIT"

[lints]
workspace = true

[dependencies]
miralis_core = { path = "../core" }
log = { workspace = true }
miralis_config = { path = "../config"}
