[package]
name = "interrupt"
version = "0.1.0"
edition = "2024"

license = "MIT"

[[bin]]
name = "interrupt"
path = "main.rs"

[dependencies]
miralis_abi = { path = "../../crates/abi" }
test_helpers = { path = "../../crates/test_helpers" }
log = { workspace = true }
