[package]
name = "test_protect_payload_payload"
version = "0.1.0"
edition = "2024"

license = "MIT"

[[bin]]
name = "test_protect_payload_payload"
path = "main.rs"

[lints]
workspace = true

[dependencies]
miralis_abi = { path = "../../crates/abi" }
